version: '3.8'

networks:
  nelly-dev:
    external: true

services:
  nginx:
    image: nginx:dev
    container_name: nginx
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      nelly-dev:
