version: '3'
services:
  nodejs:
    build:
      context: ./nodejs_test_server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  rate-limit-config-server:
    build:
      context: ./rate-limit-config-server
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  redis-init:
    image: redis:latest
    container_name: redis-init
    depends_on:
      - redis
    volumes:
      - ./limits.json:/limits.json
      - ./allowlist.json:/allowlist.json
      - ./redis-values-init.sh:/redis-values-init.sh
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "/redis-values-init.sh && echo 'Initialization done!'"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis
      - nodejs
      - rate-limit-config-server
