version: '3'
services:
  nodejs:
    build:
      context: ./nodejs_test_server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
  webdis:
    image: public.ecr.aws/nicolas/webdis:latest
    container_name: webdis
    ports:
      - "7379:7379"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - webdis
      - nodejs
