version: '3'
services:
  nodejs:
    build:
      context: ./nodejs_test_server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis
      - nodejs
