version: '3'
services:
  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "3000:3000"
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - nodejs