version: '3'
services:
  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "3000:3000"
  redis:
    image: redis:6.0.10
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - redis
      - nodejs

